language: python
dist: focal
python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9-dev"

before_install:
    - sudo apt-get install build-essential
    - sudo apt-get install libzfslinux-dev

install:
    - pip install -r requirements/development.txt
    - python setup.py build
    - python setup.py install

script:
    - pytest

notifications:
    webhooks:
        urls:
        - https://webhooks.gitter.im/e/5736d7134d30b4cdab52
        on_success: change  # options: [always|never|change] default: always
        on_failure: always  # options: [always|never|change] default: always    
    