language: python
dist: focal
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"
  - "pypy3"

before_install:
  - sudo apt-get install build-essential
  - sudo apt-get install libzfslinux-dev

install:
  - pip install -r requirements/development.txt

script:
  - python setup.py build
  - python setup.py install
